permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM
  
  
# 作者信息
author: 
  name: jurnlee
  email: jurnlee@sina.com
  link: http://blog.csdn.net/jurnlee
  weibo: http://weibo.com/jurnlee
  github: https://github.com/jurnlee

# 站点信息
title: jurnlee's blog 
description: jurnlee's blog 
url: http://jurnlee.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
#gavatar: http://img.my.csdn.net/uploads/201411/21/1416528891_3612.png
favicon:  http://img.my.csdn.net/uploads/201411/21/1416528891_9081.png

# disqus 设置
#disqus:
#  shortname: zmywly8866

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
