# 不能使用tab否则解析出错
# 每个key: value的英文冒号后面必须有空格，否则解析出错
# 调用的时候会自动按照格式与#号注释划分成{}对象,如：test2不再属于test1
test1: 
    test11:
    test12: test12msg
test2:

permalink: /:year/:month/:day/:title.html
paginate: 20
markdown: kramdown

kramdown:
  input: GFM
  
# 作者信息
author: 
    name:     xflye,jurnlee
    sitename:  xflye's inspectional world
    blogname: 筱枫夜の印象视界
    email:  jurnlee@sina.com
    link:   http://blog.csdn.net/jurnlee
    weibo:  http://weibo.com/jurnlee
    github: https://github.com/jurnlee
    lofter: http://jurnlee.lofter.com
    
# 站点信息
title: 筱枫夜の印象视界
description: 筱枫夜の印象视界 jurnlee's blog 
url: http://jurnlee.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar:  http://avatar.csdn.net/7/5/E/1_jurnlee.jpg
favicon:  http://avatar.csdn.net/7/5/E/4_jurnlee.jpg

# disqus 设置
#   disqus:    none
#   shortname: none

#-----------------定义---------------------
#调用方式: {{ site.locals.home }}
locals:
    home: 首页
    tags: 标签
    about: 关于
    newest: 最新文章
    archive: 归档
    category: 分类
    content: 目录
    contact: 联系方式
    
#  {{ site.links.tagslink }}
links:
    tagslink: /pages/tags.html
    aboutlink: /pages/about.html
    newestlink: /pages/newest.html
    archivelink: /pages/archive.html
    contentlink: /pages/content.html
    contactlink: /pages/contact.html
    categorylink: /pages/categories.html

constants:
    language: 语言
    lan_CN: 中文
    lan_EN: 英文
    othersite: 其他站点
    postat: 发布于
    detail: 详细

#首页
idx:
    bannerh1: 当你不断追求卓越的时候，成功一定会追赶你的脚步
    bannerp: 待到成功后再诉说的艰辛过程，一切都将被轻描淡写的多么清晰完美，但永远没有这样一边走一边探索出的东西真切，更具有普遍意义。<br />所以，请开始记录所有的悲愤故事，快乐故事吧。
    firstdivider: 悲愤之地，三观不定者慎观之
